services:
  nginx:
    image: nginx:alpine
    container_name: static-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./site:/usr/share/nginx/html:rw
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
    depends_on:
      - nodejs
    restart: unless-stopped

  nodejs:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/timewaitfornoonedb
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_KEYSPACE=logsystem
    volumes:
      - ./api:/usr/src/app:rw
      - /usr/src/app/node_modules
    expose:
      - 3000
    depends_on:
      - postgres
      - cassandra
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    restart: unless-stopped

  cassandra-init:
    image: cassandra:latest
    depends_on:
      - cassandra
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Waiting for Cassandra...';
      until cqlsh cassandra -e 'DESCRIBE KEYSPACES;' > /dev/null 2>&1; do sleep 2; done;
      echo 'Running schema init...';
      cqlsh cassandra -f /init-schema.cql;
      echo 'Waiting for schema agreement...';
      sleep 5;
      echo 'Running data insert...';
      cqlsh cassandra -f /init-data.cql;
      "
    volumes:
      - ./cassandra/init-schema.cql:/init-schema.cql
      - ./cassandra/init-data.cql:/init-data.cql

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    container_name: cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    restart: unless-stopped
  

volumes:
  cassandra-data:
 