#FROM cassandra:latest

# Copy init files into image
#COPY init-schema.cql /init-schema.cql
#COPY init-data.cql /init-data.cql
#COPY docker-entrypoint-init.sh /docker-entrypoint-init.sh

# Make the script executable
#RUN chmod +x /docker-entrypoint-init.sh

# Use our own startup script
#ENTRYPOINT ["/docker-entrypoint-init.sh"]
